---
centos-master:
  :box:
    :name: 'centos/6'
  :network_config:
    :hostname: 'vagrant-puppetmaster.vagrant.local'
    :networks:
    - :private: true
      :type: 'dhcp'
    :dns:
      :servers:
      - '208.67.222.222'
  :provisioning:
  - :type: 'file'
    :source: './files/tmp/pe.conf'
    :destination: '/tmp/pe.conf'

  - :type: 'file'
    :source: './files/tmp/pe-latest.tgz'
    :destination: &pe_installer_tar '/tmp/pe-latest.tgz'

  - :type: 'shell'
    :privileged: true
    :path: './scripts/configure_root_user.sh'

  - :type: 'shell'
    :privileged: true
    :path: './scripts/configure_sshd.sh'


  - :type: 'shell'
    :privileged: true
    :path: './scripts/install_puppet_enterprise.sh'
    :args:
    - 'el'
    - 'x86_64'
    - '6'
    - '2016.4.0'
    - *pe_installer_tar
    
  :ssh_config:
    :insert_key: false
  :synced_folders:
  - :local_path: './puppet-labenvironment'
    :remote_path: '/puppet_code'
  :providers:
    :virtualbox:
      :name: 'vagrant-puppet-master'
      :cores: 2
      :memory: 4096
      :guest_additions: true

centos-agent:
  :instances: 1
  :box:
    :name: 'centos/6'
  :network_config:
    :hostname: 'vagrant-centosagent.vagrant.local'
    :networks:
    - :private: true
      :type: 'dhcp'
    :dns:
      :servers:
      - '208.67.222.222'

  :provisioning:

  - :type: 'shell'
    :privileged: true
    :path: './scripts/configure_root_user.sh'

  - :type: 'shell'
    :privileged: true
    :path: './scripts/configure_sshd.sh'

  - :type: 'shell'
    :privileged: true
    :path: './scripts/install_puppet.sh'

  :ssh_config:
    :insert_key: false
  :providers:
    :virtualbox:
      :name: 'vagrant-puppet-centosagent'
      :cores: 1
      :memory: 1024

debian-agent:
  :instances: 1
  :box:
    :name: 'debian/jessie64'
  :network_config:
    :hostname: 'vagrant-debianagent.vagrant.local'
    :networks:
    - :private: true
      :type: 'dhcp'
    :dns:
      :servers:
      - '208.67.222.222'


  :provisioning:

  - :type: 'shell'
    :privileged: true
    :path: './scripts/configure_root_user.sh'

  - :type: 'shell'
    :privileged: true
    :path: './scripts/configure_sshd.sh'

  - :type: 'shell'
    :privileged: true
    :path: './scripts/install_puppet.sh'
 
  :ssh_config:
    :insert_key: false
  :providers:
    :virtualbox:
      :name: 'vagrant-puppet-debianagent'
      :cores: 1
      :memory: 1024

ubuntu-agent:
  :instances: 1
  :box:
    :name: 'ubuntu/trusty64'
  :network_config:
    :hostname: 'vagrant-ubuntuagent.vagrant.local'
    :networks:
    - :private: true
      :type: 'dhcp'
    :dns:
      :servers:
      - '208.67.222.222'


  :provisioning:

  - :type: 'shell'
    :privileged: true
    :path: './scripts/configure_root_user.sh'

  - :type: 'shell'
    :privileged: true
    :path: './scripts/configure_sshd.sh'

  - :type: 'shell'
    :privileged: true
    :path: './scripts/install_puppet.sh'

  :ssh_config:
    :insert_key: false
  :providers:
    :virtualbox:
      :name: 'vagrant-puppet-ubuntuagent'
      :cores: 1
      :memory: 1024
